// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejzkepevssvhzdkfrvfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqemtlcGV2c3N2aHpka2ZydmZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MDQ5OTAsImV4cCI6MjA2MTE4MDk5MH0.GN6FjGA_kfce81asErUnRw8ZB8MEmLMNows0WXCdPvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);